import React from "react";
import Link from "next/link";
import { Scale, ArrowLeft, AlertCircle } from "lucide-react";

export const metadata = {
  title: "Terms of Service & Medical Disclaimer — Ideat",
  description: "Terms of service, usage conditions, and clinical medical disclaimer for Ideat.",
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20">
      <Link
        href="/"
        className="inline-flex items-center gap-2 text-xs font-semibold text-emerald-400 hover:text-emerald-300 mb-8 transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Home
      </Link>

      <div className="space-y-8">
        <div className="border-b border-slate-800 pb-6">
          <div className="flex items-center gap-2 text-xs font-bold text-emerald-400 uppercase tracking-wider mb-2">
            <Scale className="w-4 h-4" /> Legal & Terms of Use
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Terms of Service & Clinical Disclaimer
          </h1>
          <p className="text-xs text-slate-400 mt-2">
            Last Updated: September 16, 2026 • Compliant with Apple App Store Review Guideline 1.4.1
          </p>
        </div>

        {/* Medical Disclaimer Alert Banner */}
        <div className="p-6 rounded-3xl bg-amber-950/30 border border-amber-500/30 space-y-3">
          <div className="flex items-center gap-2 text-amber-400 font-bold text-sm">
            <AlertCircle className="w-5 h-5 flex-shrink-0" />
            <span>Important Medical & Clinical Disclaimer</span>
          </div>
          <p className="text-xs text-amber-200/90 leading-relaxed">
            Ideat is an educational, informational tool designed to evaluate food products against published peer-reviewed dietary literature and consensus guidelines. <strong>Ideat does not provide medical advice, diagnosis, or clinical treatment.</strong> Always consult your physician, gastroenterologist, registered dietitian, or qualified healthcare professional before making clinical dietary interventions.
          </p>
        </div>

        <div className="prose prose-invert max-w-none text-slate-300 text-sm space-y-6 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-lg font-bold text-white">1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using the Ideat mobile application for iOS and watchOS, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-white">2. Scope of Educational & Informational Purpose</h2>
            <p>
              Ideat calculates nutritional metrics and matches ingredients against published clinical guidelines from leading scientific authorities including:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>American Diabetes Association (ADA) Standards of Care in Diabetes</li>
              <li>American Heart Association (AHA) Presidential Advisories on Dietary Fats and Cardiovascular Disease</li>
              <li>Harvard T.H. Chan School of Public Health Carbohydrate Quality &amp; 10:1 Ratio Standards</li>
              <li>American Institute for Cancer Research (AICR / WCRF) Guidelines</li>
              <li>American Gastroenterological Association (AGA) Clinical Practice Updates</li>
              <li>Celiac Disease Foundation &amp; FDA 21 CFR 101.91 Gluten-Free Standard</li>
              <li>University of São Paulo NOVA Food Classification System</li>
            </ul>
            <p>
              Evaluations generated by the app (including badges marked &quot;Optimal,&quot; &quot;Caution,&quot; or &quot;Contraindicated&quot;) represent algorithmic interpretations of publicly available food product packaging and database records. They do not constitute personalized clinical prescriptions.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-white">3. Allergens, Celiac Disease &amp; Critical Cross-Contact</h2>
            <p>
              While Ideat uses advanced keyword matching and optical recognition to identify common allergen and gluten triggers, <strong>food manufacturers frequently change formulations, facilities, and production lines without notice</strong>.
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-400">
              <li>Always read the physical printed packaging ingredient statement before consuming any food item.</li>
              <li>For individuals with Celiac Disease or severe anaphylactic allergies, rely exclusively on third-party certifications (e.g. GFCO, NSF, or Certified Gluten-Free seals) and direct contact with the manufacturer.</li>
              <li>Ideat assumes no liability for manufacturer packaging errors, typographical OCR misrecognitions, or unlisted shared-facility cross-contact.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-white">4. User Responsibilities &amp; License</h2>
            <p>
              Ideat grants you a personal, non-exclusive, non-transferable, revocable license to use the app on authorized Apple devices. You agree not to decompile, reverse-engineer, or attempt to extract source code or proprietary datasets without express written authorization.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-white">5. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, in no event shall Ideat, its developers, or contributors be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of your access to or use of the application.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-bold text-white">6. Changes to Terms</h2>
            <p>
              We reserve the right to update these terms at any time. Continued use of the application following updates constitutes acceptance of the modified terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
